### ISSUE TITLE
[Feature request]  remember last items

### ISSUE THREAD

**Issue by roya0045** [sandroklippel/qgis_gee_data_catalog#3]
Greetings, 

In the PR that I made I recalled that some elements remained saved, now in the latest release those elements reset. Could it be possible to have those elements remain whenever the plugin is reopened.

I don't recall how to cache them or what is causing them to reset but resetting the output each time along with other parameters is more annoying as our use case require to only need to change 1 or two element between each export.

Thanks again,

**Comment by sandroklippel** [comment]
Do you remember which elements? I didn't see these changes in PR. I'll
revise it as soon as possible.

Em qui., 8 de out. de 2020 às 12:20, Alex <notifications@github.com>
escreveu:

**Comment by roya0045** [comment]
I'm not sure how it happened. I've looked at your fixes and nothing stands out. An option to remember the last directory would be to store the variable in the plugin instance and not the dialog instance. Just by changing https://github.com/sandroklippel/qgis_gee_data_catalog/blob/6e5d89240ebb68d0f16620542c2aabf59e1a09a2/qgis_gee_data_catalog_dialog_base.py#L90 and adding a check if the folder variable is set before providing the default.

Or maybe it was a thing I changed and I opted to don't remember it as users had no way to 'reset' the variable (but any invalid folder would cause a temporary output to be created).

I can do a PR and some tests if you don't want or hhave the time to do so. I may have enough time during the weekend.

**Comment by sandroklippel** [comment]
Sorry, it was my fault. Just comment out line 431 in
qgis_gee_data_catalog.py

Em qui., 8 de out. de 2020 às 18:17, Alex <notifications@github.com>
escreveu:

**Comment by sandroklippel** [comment]
I just commited the fix. If you can do some testing, maybe we can release a minor version after the weekend.

**Comment by roya0045** [comment]
Excellent, thanks! We'll try to do some testing today.

**Comment by roya0045** [comment]
Did a quick test, all seemed fine, the last folder string remained and the output was constant. Thanks again Sandro!

**Comment by sandroklippel** [comment]
Issue fixed, version 0.4.1 released.

**Comment by roya0045** [comment]
Thanks Sandro for the great support!
