### ISSUE TITLE
'earthengine' is not recognized as an internal or external command [Windows 10]

### ISSUE THREAD

**Issue by nafarinha** [sandroklippel/qgis_gee_data_catalog#4]
Hi, I tried following the [installation guide](https://github.com/sandroklippel/qgis_gee_data_catalog/wiki/Instalacao) but when I try to run `earthengine authenticate`, it fails. I couldn't find anything that could point me what might me wrong on my side. This is what I get on the OSGeo4W Shell:

```
C:\>earthagine authenticate
'earthagine' is not recognized as an internal or external command,
operable program or batch file.
````

Any help is appreciated!

**Comment by sandroklippel** [comment]
Are you sure you typed the program name correctly?
C:\>earthengine authenticate

**Comment by sandroklippel** [comment]
Also, remember that it is necessary to type inside the OSGeo4W Shell after the command "call py3_env.bat"

**Comment by nafarinha** [comment]
Thanks for the reply! This is exactly what I typed and got back on OSGeo4W Shell:

```
run o-help for a list of available commands
C:\>call py3_env.bat

C:\>SET PYTHONHOME=C:\PROGRA~1\QGIS3~1.10\apps\Python37

C:\>SET PYTHONPATH=C:\PROGRA~1\QGIS3~1.10\apps\Python37;C:\PROGRA~1\QGIS3~1.10\apps\Python37\Scripts

C:\>PATH C:\PROGRA~1\QGIS3~1.10\apps\Python37;C:\PROGRA~1\QGIS3~1.10\apps\Python37\Scripts;C:\PROGRA~1\QGIS3~1.10\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\system32\WBem

C:\>earthengine authenticate
'earthengine' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by sandroklippel** [comment]
README.md updated with new instructions
