### ISSUE TITLE
Data are not downloadable

### ISSUE THREAD

**Issue by knussear** [sandroklippel/qgis_gee_data_catalog#8]
I am able to search and download the imagery fine, but they all come in at a resolution of 0.29 m and when trying to export or calculate indices I get a file size is too large error.

**Comment by sandroklippel** [comment]
You must download it with the option in the context menu. The image will be downloaded to your google drive with the original resolution and with the current (project) CRS
![downdload_to_gdrive](https://user-images.githubusercontent.com/33760784/157903803-38f25bf5-6070-4046-a1f4-cc53d6927dd4.gif)
.
